/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package game;

import city.cs.engine.SoundClip;
import static game.Game.menuname;
import static game.Game.menuscore;
import java.io.IOException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFrame;

/**
 * @author Steve Odai-Stephens
 */
public class MenuStart extends javax.swing.JPanel {

    /**
     * variable of SoundClip class 
     */
    private SoundClip gameMusic;
    
    /** 
     * Creates new form StartMenu 
     */
    public MenuStart() {
        initComponents();
        try {
            gameMusic = new SoundClip("data/menu.mp3");
            gameMusic.loop();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println(e);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        start = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        highscores = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        start.setBackground(new java.awt.Color(0, 0, 0));
        start.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        start.setForeground(new java.awt.Color(255, 255, 255));
        start.setText("START GAME");
        start.setBorderPainted(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("EXIT");
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SMAUG RETURNS: DARK ECLIPSE");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/menubackground.gif"))); // NOI18N
        jLabel2.setText("jLabel2");

        highscores.setBackground(new java.awt.Color(0, 0, 0));
        highscores.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        highscores.setForeground(new java.awt.Color(255, 255, 255));
        highscores.setText("HIGH SCORES");
        highscores.setBorderPainted(false);
        highscores.setContentAreaFilled(false);
        highscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highscoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(highscores, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(start)
                .addGap(27, 27, 27)
                .addComponent(highscores)
                .addGap(27, 27, 27)
                .addComponent(exit))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        gameMusic.stop();
            // TODO add your handling code here:
        MenuEnterName start1 = new MenuEnterName();
        start1.setVisible(true);
        
        menuname.setSize(670,110);
        menuname.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        menuname.setVisible(true);
        menuname.add(start1);
        Game.menu.dispose();
    }//GEN-LAST:event_startActionPerformed

    private void highscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highscoresActionPerformed
        // TODO add your handling code here:
        gameMusic.stop();
            // TODO add your handling code here:
        MenuHighscores start2 = new MenuHighscores();
        start2.setVisible(true);
        
        menuscore.setSize(243,600);
        menuscore.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        menuscore.setVisible(true);
        menuscore.add(start2);
        Game.menu.dispose();
    }//GEN-LAST:event_highscoresActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton highscores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables

}
