
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import city.cs.engine.*;

/**
 * @author Steve Odai-Stephens
 */
public class MenuTop extends javax.swing.JPanel {

    /**
     * The World in which the bodies move and interact.
     */
    private World world;

    /**
     * Creates new form MenuTop
     * @param world the world
     */
    public MenuTop(World world) {
        this.world = world;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pause = new javax.swing.JButton();
        resume = new javax.swing.JButton();
        quit = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));

        pause.setBackground(new java.awt.Color(0, 0, 0));
        pause.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        pause.setForeground(new java.awt.Color(255, 255, 255));
        pause.setText("PAUSE");
        pause.setBorderPainted(false);
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });

        resume.setBackground(new java.awt.Color(0, 0, 0));
        resume.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        resume.setForeground(new java.awt.Color(255, 255, 255));
        resume.setText("RESUME");
        resume.setBorderPainted(false);
        resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeActionPerformed(evt);
            }
        });

        quit.setBackground(new java.awt.Color(0, 0, 0));
        quit.setFont(new java.awt.Font("Papyrus", 0, 24)); // NOI18N
        quit.setForeground(new java.awt.Color(255, 255, 255));
        quit.setText("QUIT");
        quit.setBorderPainted(false);
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pause, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(resume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(quit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pause)
                .addComponent(resume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quit))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        // TODO add your handling code here:
        world.stop();
    }//GEN-LAST:event_pauseActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void resumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeActionPerformed
        // TODO add your handling code here:
        world.start();
    }//GEN-LAST:event_resumeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton pause;
    private javax.swing.JButton quit;
    private javax.swing.JButton resume;
    // End of variables declaration//GEN-END:variables
}
